---
apiVersion: v1
kind: Service
metadata:
spec:
  type: NodePort
  selector:
    app:  name: nginx-svc
 nginx
    ver: "1.23"
  ports:
    - webport:
      port: 3500
      targetport: 80
      nodeport: 8080    